name: CMake

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup
      uses: ilammy/msvc-dev-cmd@v1.13.0
      with:
        arch: x86

    - name: Cache bin
      id: cache-bin
      uses: actions/cache@v4
      with:
        path: bin
        key: ${{ runner.os }}-bin

    - name: Create bin folder
      if: steps.cache-bin.outputs.cache-hit != 'true'
      run: |
        mkdir bin
        cd bin
        cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release ../
        mkdir output_III
        mkdir output_VC
        mkdir output_SA
    
    - name: Compile
      run: |
        cd bin
        ninja
        cp ChaosModComplementaries.III.asi output_III/ChaosModComplementaries.III.asi
        cp ChaosModComplementaries.VC.asi output_VC/ChaosModComplementaries.VC.asi
        cp ChaosModComplementaries.SA.asi output_SA/ChaosModComplementaries.SA.asi

    - name: Upload III
      uses: actions/upload-artifact@v4
      with:
        name: "ChaosModComplementaries.III"
        path: bin/output_III

    - name: Upload VC
      uses: actions/upload-artifact@v4
      with:
        name: "ChaosModComplementaries.VC"
        path: bin/output_VC
        
    - name: Upload SA
      uses: actions/upload-artifact@v4
      with:
        name: "ChaosModComplementaries.SA"
        path: bin/output_SA
  
