name: Build And Create Artifacts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      PLUGIN_SDK_DIR: ${{ github.workspace }}/plugin-sdk

    steps:
    # 1. Setup x86 MSVC environment for Ninja & CMake
    - name: Setup x86 MSVC Command Prompt
      uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
        arch: x86

    # 2. Checkout main project repository
    - name: Checkout ChaosModComplementaries
      uses: actions/checkout@v7

    # 3. Clone PluginSDK into 'plugin-sdk'
    - name: Clone PluginSDK
      shell: cmd
      run: |
        if not exist plugin-sdk (
            git clone https://github.com/DK22Pac/plugin-sdk.git plugin-sdk
            cd plugin-sdk
            git checkout 15f15b60bbf74c106e1b496ff92c98764abf4605
        )

    # 4. Cache compiled PluginSDK static libraries
    - name: Cache PluginSDK Output
      id: cache-pluginsdk
      uses: actions/cache@v6
      with:
        path: plugin-sdk/output
        key: pluginsdk-${{ runner.os }}-${{ hashFiles('plugin-sdk/**') }}

    - name: Setup MSBuild
      if: steps.cache-pluginsdk.outputs.cache-hit != 'true'
      uses: microsoft/setup-msbuild@v3

    # 5. Generate and build PluginSDK ONLY if cache missed
    - name: Generate PluginSDK Solution via Premake
      if: steps.cache-pluginsdk.outputs.cache-hit != 'true'
      run: |
        & "$env:PLUGIN_SDK_DIR\tools\premake\premake5.exe" vs2026 --file="$env:PLUGIN_SDK_DIR\tools\premake\premake5.lua"

    - name: Build PluginSDK Static Libraries
      if: steps.cache-pluginsdk.outputs.cache-hit != 'true'
      shell: cmd
      run: msbuild "%PLUGIN_SDK_DIR%\plugin_sa\Plugin_SA.vcxproj" /p:Configuration=Release /p:Platform=Win32 /m

    # 6. Configure and Build CMake project
    - name: Configure CMake
      run: |
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

    - name: Compile Plugins
      run: |
        cmake --build build --config Release

    # 7. Organize output into designated directory
    - name: Organize Output Folder
      shell: cmd
      run: |
        if not exist build\output mkdir build\output
        if exist build\ChaosModComplementaries.SA.asi copy build\ChaosModComplementaries.SA.asi build\output\

    # 8. Upload ASI artifact

    - name: Upload SA Artifact
      uses: actions/upload-artifact@v7
      with:
        name: "ChaosModComplementaries.SA"
        path: build/output/
        if-no-files-found: ignore